version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    restart: always
    ports:
      - 8080:80

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    restart: always
    ports:
      - 3333:3333

  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306

    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  mysql_data: {}
